//? app layout

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Nav from "@/components/nav";
import Footer from "@/components/footer";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

const silka = localFont({
  src: [
    {
      path: "../fonts/silka-bold-webfont.ttf",
      style: "normal",
      weight: "700",
    },
    {
      path: "../fonts/silka-medium-webfont.ttf",
      style: "normal",
      weight: "500",
    },
    {
      path: "../fonts/silka-light-webfont.ttf",
      style: "normal",
      weight: "300",
    },
  ],
  variable: "--font-silka",
});

export const metadata: Metadata = {
  title: "GFrame | Vaše firma na cloudu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${silka.variable} ${poppins.variable}`}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
